# Generated by Django 3.0.8 on 2020-07-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sed_number', models.CharField(max_length=40, verbose_name='Номер СЭД')),
                ('out_number', models.CharField(blank=True, max_length=40, verbose_name='Внешний номер')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('reg_date', models.DateTimeField(blank=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-reg_date', 'name', 'sed_number'],
            },
        ),
    ]
