# Generated by Django 3.0.8 on 2020-07-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_team_info'),
        ('document', '0002_auto_20200724_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Состояние документа')),
                ('status_order', models.PositiveIntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Состояние документа',
                'verbose_name_plural': 'Состояния документов',
                'ordering': ['status_order', 'status'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.Project', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_agreement', models.PositiveIntegerField(blank=True, verbose_name='Номер ДС')),
                ('document', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='document.Contract', verbose_name='Родительский договор (если ДС)')),
            ],
            options={
                'verbose_name': 'Договор / ДС',
                'verbose_name_plural': 'Договоры / ДС',
                'ordering': ['document'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='document.DocumentStatus', verbose_name='Состояние документа'),
        ),
    ]
