# Generated by Django 3.0.8 on 2020-07-27 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200723_1722'),
        ('document', '0003_auto_20200727_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document.Document', verbose_name='Письмо')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='contact.Company', verbose_name='Отправитель')),
                ('to', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='to', to='contact.Company', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['sender', 'to'],
            },
        ),
    ]
