# Generated by Django 3.0.9 on 2020-08-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='control',
            field=models.BooleanField(default=True, verbose_name='На контроле'),
        ),
    ]
