# Generated by Django 3.0.9 on 2020-08-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_document_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата комментария')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document.Document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date'],
            },
        ),
    ]
