# Generated by Django 3.0.8 on 2020-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Адрес электронной почты')),
            ],
        ),
        migrations.CreateModel(
            name='Skype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skype', models.CharField(max_length=100, verbose_name='Skype')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='post',
            field=models.CharField(default='empty', max_length=100, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='emails',
            field=models.ManyToManyField(to='contact.Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='skypes',
            field=models.ManyToManyField(to='contact.Skype'),
        ),
    ]
