# Generated by Django 3.0.8 on 2020-07-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200723_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['short_name'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['email'], 'verbose_name': 'Адрес электронной почты', 'verbose_name_plural': 'Адреса электронной почты'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['phone_number'], 'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterModelOptions(
            name='skype',
            options={'ordering': ['skype'], 'verbose_name': 'Skype-логин', 'verbose_name_plural': 'Skype-логины'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='emails',
            field=models.ManyToManyField(to='contact.Email', verbose_name='Адреса электронной почты'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phones',
            field=models.ManyToManyField(to='contact.Phone', verbose_name='Телефоны'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='skypes',
            field=models.ManyToManyField(to='contact.Skype', verbose_name='Skype-логины'),
        ),
        migrations.AlterField(
            model_name='skype',
            name='skype',
            field=models.CharField(max_length=100, verbose_name='Skype-логин'),
        ),
    ]
