# Generated by Django 3.0.8 on 2020-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20200727_1853'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='documents',
            field=models.ManyToManyField(blank=True, to='document.Document', verbose_name='Отчетные документы'),
        ),
    ]
