# Generated by Django 3.0.8 on 2020-07-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['task', 'comment_date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RenameField(
            model_name='taskcomment',
            old_name='plan_end_date',
            new_name='comment_date',
        ),
    ]
