# Generated by Django 3.0.8 on 2020-07-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['abbr_name'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
