# Generated by Django 3.0.8 on 2020-07-27 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200723_1722'),
        ('project', '0002_auto_20200723_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Роль в проекте')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100, verbose_name='Название команды')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.Contact', verbose_name='Имя')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Project', verbose_name='Проект')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['project', 'team_name', 'name', 'role'],
            },
        ),
    ]
