# Generated by Django 3.0.8 on 2020-07-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_team_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='info',
            field=models.CharField(blank=True, max_length=500, verbose_name='Зона ответственности, задачи'),
        ),
    ]
